import './base.js';
import { Header } from './components/Header/Header.js';
import { Board } from './components/Boards/board.js';
import { Footer } from './components/Footer/Footer.js';
import './components/events/backlogEvent.js';
import './components/events/readyEvent.js';
import './components/events/inprogressEvent.js';
import './components/events/finishedEvent.js';
import './components/events/dropdownEvent.js';
import './components/events/loadEvent.js';

const header = new Header();
const backlog = new Board('Backlog', 'backlog');
const ready = new Board('Ready', 'ready');
const inprogress = new Board('In Progress', 'inprogress');
const finished = new Board('Finished', 'finished');
const footer = new Footer();

document.body.appendChild(header.element);
addDropdown();
removeDropdown();
document.body.appendChild(backlog.element);
addTaskBacklog();
document.body.appendChild(ready.element);
createListTaskReady();
addTaskReady();
document.body.appendChild(inprogress.element);
createListTaskInprogress();
addTaskInprogress();
document.body.appendChild(finished.element);
createListTaskFinished();
addTaskFinished();
document.body.appendChild(footer.element);
loadBoard();
